x-app-common: &app-common
  build:
    context: .
    dockerfile: ./.docker/php/Dockerfile
  volumes:
    - ./src:/var/www/html
  environment:
    APP_ENV: local
    APP_DEBUG: "true"
    APP_URL: http://localhost
    OCTANE_SERVER: swoole
    OCTANE_MAX_REQUESTS: 500
    PHP_MEMORY_LIMIT: 512M
    PHP_OPCACHE_ENABLE: 1
    PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
    PHP_OPCACHE_MAX_ACCELERATED_FILES: 20000
    DB_HOST: mysql
    DB_PORT: 3306
    DB_DATABASE: laravel
    DB_USERNAME: laravel
    DB_PASSWORD: laravel
    REDIS_HOST: redis
    REDIS_PORT: 6379
    MAIL_MAILER: smtp
    MAIL_HOST: mailpit
    MAIL_PORT: 1025
  depends_on:
    - mysql
    - redis

services:
  # 1) Ứng dụng chạy Octane (Swoole)
  app:
    <<: *app-common
    container_name: app-octane
    environment:
      OCTANE_WATCHER: inotify
#    command: sh -lc "php artisan migrate --force || true && php artisan octane:start --server=swoole --host=0.0.0.0 --port=8000 --watch"
    command: sh -lc "php artisan migrate --force || true && php artisan octane:start --server=swoole --host=0.0.0.0 --port=8000"

    expose:
      - "8000"

  # 2) Nginx reverse proxy -> app:8000
  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

  # 3) Queue Worker
  queue:
    <<: *app-common
    container_name: queue-worker
    command: sh -lc "php artisan queue:work --tries=3 --timeout=90 --verbose"

  # 4) Scheduler (cron chạy mỗi phút)
  scheduler:
    <<: *app-common
    container_name: scheduler
    command: sh -lc 'while [ true ]; do php artisan schedule:run --verbose --no-interaction; sleep 60; done'

  # 5) MySQL 8
  mysql:
    image: mysql:8.0
    container_name: mysql
    command: >
      mysqld --character-set-server=utf8mb4
             --collation-server=utf8mb4_unicode_ci
             --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # 6) Redis
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  # 7) Mailpit (SMTP test)
  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "8025:8025" # UI http://localhost:8025
      - "1025:1025" # SMTP

volumes:
  mysql_data:
